- name: Logging in to OpenShift
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Ensure an access token is retrieved for the developer user
      redhat.openshift.openshift_auth:
        host: https://api.ocp4.example.com:6443
        username: developer
        password: developer
        ca_cert: /etc/pki/tls/certs/ca-bundle.crt
      register: auth_results
- name: Deploying the intranet front end application
  hosts: localhost
  vars:
    project: intranet-front

  module_defaults:
    group/redhat.openshift.openshift:
      namespace: "{{ project }}"
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.ocp4.example.com:6443
      ca_cert: /etc/pki/tls/certs/ca-bundle.crt
    group/kubernetes.core.k8s:
      namespace: "{{ project }}"
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.ocp4.example.com:6443
      ca_cert: /etc/pki/tls/certs/ca-bundle.crt
  tasks:
    - name: Ensure the project exists
      redhat.openshift.k8s:
        state: present
        resource_definition:
          apiVersion: project.openshift.io/v1    
          kind: Project
          metadata:
            name: "{{project}}" 
    - name: Ensure the intranet front end is deployed
      redhat.openshift.k8s:
        state: present
        src: intranet-front.yaml
    - name: Ensure the deployments is scaled up
      kubernetes.core.k8s_scale:
        kind: Deployment
        name: hello
        replicas: 5
    - name: Ensure a route exists
      redhat.openshift.openshift_route: 
        service: hello
      register: route
    - name: Ensure the route is displayed
      debug:
        msg: "The Intranet is available at
              http://{{ route['result']['spec']['host'] }}"

          
