- name: Logging in to OpenShift
  hosts: localhost
  tasks:
    - name: Ensure an access token is retrieved for the developer user
      redhat.openshift.openshift_auth:
        host: https://api.example.com:6443
        username: developer
        password: developer
      register: auth_results
- name: Deploying the intranet front end application
  hosts: localhost
  module_defaults:
    group/redhat.openshift.openshift:
      namespace: intranet-front
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.example.com:6443
    group/kubernetes.core.k8s:
      namespace: intranet-front
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.example.com:6443
  tasks:
    - name: Ensure the project exists
      redhat.openshift.k8s:
        state: present
        resource_definition:
          apiVersion: project.openshift.io/v1    
        kind: Project
       metadata:
          name: intranet-front  
    - name: Ensure the intranet front end is deployed
      redhat.openshift.k8s:
        state: present
        src: intranet-front.yml
    - name: Ensure the deployments is scaled up
      kubernetes.core.k8s_scale:
        kind: Deployment
        name: intranet-front
        replicas: 5
    - name: Ensure a route exists
      redhat.openshift.openshift_route: 
        service: intranet-front-svc
      register: route
    - name: Ensure the route is displayed
      debug:
        msg: "The Intranet is available at
              http://{{ route['result']['spec']['host'] }}"

          
