---
- name: Demo of ansible playbook to automate tasks in Openshift
  hosts: all
  vars:
   myuser: admin
   mypass: redhat
   api_url: https://api.ocp4.example.com:6443
   namespace: devops200
  module_defaults:
   group/k8s:
   namespace: "{{ namespace }}"
   host: "{{api_url}}"
   validate_certs: false
  tasks:
   - name: Login to openshift
     k8s_auth:
      host: "{{api_url}}"
      username: "{{myuser}}"
      password: "{{mypass}}"
      validate_certs: false
     register: k8s_auth_results
   - name: Expose http port with ClusterIP
     k8s_service:
      state: present
      namespace: "{{ namespace }}"
      name: hello
      ports:
       - port: 8080
         name: "8080"
         protocol: TCP
         targetPort: 8080
      selector:
       app: hello

