---
- name: Demo of ansible playbook to automate tasks in Openshift
  hosts: all
  vars:
   myuser: admin
   mypass: redhat
   api_url: https://api.ocp4.example.com:6443
   namespace: devops200
  module_defaults:
   group/k8s:
   namespace: "{{ namespace }}"
   host: "{{api_url}}"
   validate_certs: false
  tasks:
   - name: Login to openshift
     k8s_auth:
      host: "{{api_url}}"
      username: "{{myuser}}"
      password: "{{mypass}}"
      validate_certs: false
     register: k8s_auth_results
   - name: Get a info about Pods that are hello apps in dev or test
     k8s_info:
      kind: Pod
      namespace: devops200
      label_selectors:
        - app = hello
   - name: Get a info about service 
     k8s_info:
      kind: Service
      namespace: devops200
     register: svc_out
   - name: Print SVC details
     debug:
      var: svc_out
