---
- name: Demo of ansible playbook to automate tasks in Openshift
  hosts: all
  vars:
   myuser: anand-pavithran
   mypass: 792101323cd74a35a104
   api_url: https://api.ap45.prod.nextcle.com:6443
   namespace: devops200
  module_defaults:
   group/k8s:
   namespace: "{{ namespace }}"
   host: "{{api_url}}"
   validate_certs: true 
  tasks:
   - name: Login to openshift
     k8s_auth:
      host: "{{api_url}}"
      username: "{{myuser}}"
      password: "{{mypass}}"
      validate_certs: true
     register: k8s_auth_results
   - name: Scale deployment up
     k8s_scale:
      kind: Deployment
      name: hello
      #api_version: "apps/v1"
      namespace: "{{namespace}}"
      #api_key: "{{k8s_auth_results.k8s_auth.api_key}}"
      replicas: 3
